#!/bin/bash

# moving all files to root
echo 'moving all files to root...'
mv ./srcs/*.c .
mv ./bonus_srcs/*.c .
mv ./includes/libft.h .
sleep 2

# deleting all forbidden folders and files for production
echo 'Deleting all forbidden files and folders for production...'
rm -rf tests/ subjects/ includes/ srcs/ bonus_srcs/ .gitignore README.md
sleep 2

# deleteing ft_memccpy.c
echo 'Deleting ft_memccpy.c...'
rm ft_memccpy.c
sleep 2

# Remove old Makefile and making a new one
echo 'Removing old Makefile and making a new one for production'
rm Makefile
mv mfile Makefile
sleep 2

echo 'PROJECT READY FOR PRODUCTION'
sleep 1

echo 'DELETING SCRIPT...'
echo 'DONE :)'
rm production